services:
  chessmorize:
    container_name: chessmorize
    image: chessmorize:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: unless-stopped
